# Generated by Django 4.2.18 on 2025-02-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='itemtype',
            field=models.CharField(choices=[('入金', '入金'), ('自動引落', '自動引落'), ('個別支払', '個別支払')], default='入金', max_length=10),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
