# Generated by Django 4.2.18 on 2025-02-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_itemtype_delete_itemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='actual_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='expected_amount',
            new_name='default_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='actual',
            field=models.BooleanField(default=False),
        ),
    ]
