# Generated by Django 4.2.18 on 2025-03-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_rename_actual_amount_budget_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('bank_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('connected_number', models.CharField(blank=True, help_text='連結番号。連結中はドラッグ不可', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='connected_number',
            field=models.CharField(blank=True, help_text='連結番号。連結中はドラッグできなくする等の制御に使用', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ConnectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.bankdata')),
                ('budget_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.connect')),
            ],
        ),
    ]
