# Generated by Django 4.2.18 on 2025-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_bankdata_connect_budget_connected_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='connected_number',
            field=models.CharField(blank=True, help_text='連結番号(連結中はドラッグ不可)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='connected_number',
            field=models.CharField(blank=True, help_text='連結番号(連結中はドラッグ不可)', max_length=20, null=True),
        ),
    ]
