# Generated by Django 4.2.18 on 2025-03-05 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0005_alter_bankdata_connected_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=10, verbose_name='銀行コード')),
                ('deposit_type', models.CharField(max_length=50, verbose_name='預金区分')),
                ('account_number', models.CharField(max_length=50, verbose_name='口座番号')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='year_month',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='年月(YYYYMM形式想定)'),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='connected_number',
            field=models.CharField(blank=True, help_text='連結番号 (連結中はドラッグ不可)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='connected_number',
            field=models.CharField(blank=True, help_text='連結番号 (連結中はドラッグ不可)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(default='', max_length=6, verbose_name='選択中の年月')),
                ('selected_account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode', verbose_name='選択中の口座コード')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6, verbose_name='年月(YYYYMM形式想定)')),
                ('beginning_balance', models.IntegerField(verbose_name='月初残高')),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.accountcode', verbose_name='口座コード')),
            ],
        ),
        migrations.AddField(
            model_name='bankdata',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode', verbose_name='口座コード'),
        ),
        migrations.AddField(
            model_name='budget',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode', verbose_name='口座コード'),
        ),
    ]
