# Generated by Django 4.2.18 on 2025-03-06 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_accountcode_budget_year_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='sort_no1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え1（2桁）'),
        ),
        migrations.AddField(
            model_name='budget',
            name='sort_no2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え2（3桁）'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='account_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.accountcode'),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='beginning_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='year_month',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='bank_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='deposit_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode'),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='connected_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='connected_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year_month',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='selected_account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='year_month',
            field=models.CharField(default='', max_length=6),
        ),
    ]
