# Generated by Django 4.2.18 on 2025-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_daterange_end_day_daterange_start_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='connectflag',
            field=models.BooleanField(default=False, verbose_name='選択中の連携区分'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='end_day',
            field=models.IntegerField(default=0, verbose_name='選択中の日付'),
        ),
    ]
