# Generated by Django 4.2.18 on 2025-03-12 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_usersettings_connectflag_usersettings_end_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('itemtype', models.CharField(choices=[('入金', '入金'), ('自動引落', '自動引落'), ('個別支払', '個別支払')], default='入金', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('specific_month', models.PositiveSmallIntegerField(default=99, verbose_name='発生月 (99=毎月, 他=単月)')),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.accountcode')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='base_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_entries', to='budget.basebudget'),
        ),
    ]
