# Generated by Django 4.2.18 on 2025-03-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_basebudget_budget_base_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='default_amount',
        ),
    ]
