# Generated by Django 4.2.18 on 2025-03-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_remove_budget_actual_remove_budget_default_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='codename',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
