# Generated by Django 4.2.18 on 2025-03-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_usersettings_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='codename',
            field=models.CharField(default='', max_length=8),
        ),
    ]
