# Generated by Django 4.2.18 on 2025-03-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_usersettings_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebudget',
            name='daterange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.daterange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basebudget',
            name='sort_no1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え（日付）'),
        ),
        migrations.AddField(
            model_name='basebudget',
            name='sort_no2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え（自由）'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sort_no1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え1（日付）'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sort_no2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='並べ替え2（自由）'),
        ),
    ]
