# Generated by Django 4.2.18 on 2025-03-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_alter_budget_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebudget',
            name='itemtype',
            field=models.CharField(choices=[('その他入金', 'その他入金'), ('自動引落', '自動引落'), ('個別支払', '個別支払')], default='入金', max_length=10),
        ),
    ]
