# Generated by Django 4.2.18 on 2025-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_alter_basebudget_itemtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='bank_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
