# Generated by Django 5.2 on 2025-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_bankdata_bank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='銀行名')),
                ('account_type', models.CharField(max_length=50, verbose_name='口座種別')),
                ('account_number', models.CharField(max_length=20, verbose_name='口座番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '銀行口座',
                'verbose_name_plural': '銀行口座',
            },
        ),
    ]
