# Generated by Django 5.2.1 on 2025-05-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_bankdata_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
